/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkylator_app;

/**
 *
 * @author jako470a
 */
public class Kalkylator extends javax.swing.JFrame {
double firstnum;
double secondnum;
double result;
String operations;
String answer;


    /**
     * Creates new form calculator
     */
    public Kalkylator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDisplay = new javax.swing.JTextField();
        jBtnBackSpc = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnExponent = new javax.swing.JButton();
        jBtnDivision = new javax.swing.JButton();
        jBtnNum7 = new javax.swing.JButton();
        jBtnNum8 = new javax.swing.JButton();
        jBtnNum9 = new javax.swing.JButton();
        jBtnSubtraktion = new javax.swing.JButton();
        jBtnNum4 = new javax.swing.JButton();
        jBtnNum5 = new javax.swing.JButton();
        jBtnNum6 = new javax.swing.JButton();
        jBtnMultiplikation = new javax.swing.JButton();
        jBtnNum1 = new javax.swing.JButton();
        jBtnNum2 = new javax.swing.JButton();
        jBtnNum3 = new javax.swing.JButton();
        jBtnAddition = new javax.swing.JButton();
        jBtnNum0 = new javax.swing.JButton();
        jBtnDecimal = new javax.swing.JButton();
        jBtnPosNeg = new javax.swing.JButton();
        jBtnSvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkylator");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 500));
        setType(java.awt.Window.Type.UTILITY);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        jBtnBackSpc.setText("<-");
        jBtnBackSpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackSpcActionPerformed(evt);
            }
        });

        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnExponent.setText("x²");
        jBtnExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExponentActionPerformed(evt);
            }
        });

        jBtnDivision.setText("/");
        jBtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivisionActionPerformed(evt);
            }
        });

        jBtnNum7.setText("7");
        jBtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum7ActionPerformed(evt);
            }
        });

        jBtnNum8.setText("8");
        jBtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum8ActionPerformed(evt);
            }
        });

        jBtnNum9.setText("9");
        jBtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum9ActionPerformed(evt);
            }
        });

        jBtnSubtraktion.setText("-");
        jBtnSubtraktion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtraktionActionPerformed(evt);
            }
        });

        jBtnNum4.setText("4");
        jBtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum4ActionPerformed(evt);
            }
        });

        jBtnNum5.setText("5");
        jBtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum5ActionPerformed(evt);
            }
        });

        jBtnNum6.setText("6");
        jBtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum6ActionPerformed(evt);
            }
        });

        jBtnMultiplikation.setText("*");
        jBtnMultiplikation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplikationActionPerformed(evt);
            }
        });

        jBtnNum1.setText("1");
        jBtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum1ActionPerformed(evt);
            }
        });

        jBtnNum2.setText("2");
        jBtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum2ActionPerformed(evt);
            }
        });

        jBtnNum3.setText("3");
        jBtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum3ActionPerformed(evt);
            }
        });

        jBtnAddition.setText("+");
        jBtnAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdditionActionPerformed(evt);
            }
        });

        jBtnNum0.setText("0");
        jBtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNum0ActionPerformed(evt);
            }
        });

        jBtnDecimal.setText(".");
        jBtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecimalActionPerformed(evt);
            }
        });

        jBtnPosNeg.setText("+/-");
        jBtnPosNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPosNegActionPerformed(evt);
            }
        });

        jBtnSvar.setText("=");
        jBtnSvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnBackSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSubtraktion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnMultiplikation, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBackSpc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSubtraktion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMultiplikation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackSpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackSpcActionPerformed
         String backspace=null;
         
        if(jtxtDisplay.getText().length() > 0){
        StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
        strB.deleteCharAt(jtxtDisplay.getText().length()-1);
        backspace = strB.toString();
        jtxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jBtnBackSpcActionPerformed

    private void jBtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum7ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum7.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum7ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum8ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum8.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum8ActionPerformed

    private void jBtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum9ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum9.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum9ActionPerformed

    private void jBtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum4ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum4.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum4ActionPerformed

    private void jBtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum5ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum5.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum5ActionPerformed

    private void jBtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum6ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum6.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum6ActionPerformed

    private void jBtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum1ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum1.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum1ActionPerformed

    private void jBtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum2ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum2.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum2ActionPerformed

    private void jBtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum3ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum3.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum3ActionPerformed

    private void jBtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNum0ActionPerformed
        String Enternumber = jtxtDisplay.getText () + jBtnNum0.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnNum0ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
    
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jBtnExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExponentActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations = "^";
    }//GEN-LAST:event_jBtnExponentActionPerformed

    private void jBtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivisionActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_jBtnDivisionActionPerformed

    private void jBtnSubtraktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtraktionActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_jBtnSubtraktionActionPerformed

    private void jBtnMultiplikationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplikationActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_jBtnMultiplikationActionPerformed

    private void jBtnAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdditionActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_jBtnAdditionActionPerformed

    private void jBtnPosNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPosNegActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnPosNegActionPerformed

    private void jBtnSvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSvarActionPerformed
        String answer;
        secondnum = Double.parseDouble(jtxtDisplay.getText());
        if (operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.0f",result);
            jtxtDisplay.setText(answer);
            
        }
        else if (operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.0f",result);
            jtxtDisplay.setText(answer);
            
        }
        else if (operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.0f",result);
            jtxtDisplay.setText(answer);
            
        }
        else if (operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.0f",result);
            jtxtDisplay.setText(answer);   
            
        }
        else if (operations == "^")
        {
            result = Math.pow(firstnum, secondnum);
            answer = String.format("%.0f",result);
            jtxtDisplay.setText(answer);   
    }//GEN-LAST:event_jBtnSvarActionPerformed

    private void jBtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDecimalActionPerformed

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkylator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkylator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkylator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkylator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkylator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddition;
    private javax.swing.JButton jBtnBackSpc;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDecimal;
    private javax.swing.JButton jBtnDivision;
    private javax.swing.JButton jBtnExponent;
    private javax.swing.JButton jBtnMultiplikation;
    private javax.swing.JButton jBtnNum0;
    private javax.swing.JButton jBtnNum1;
    private javax.swing.JButton jBtnNum2;
    private javax.swing.JButton jBtnNum3;
    private javax.swing.JButton jBtnNum4;
    private javax.swing.JButton jBtnNum5;
    private javax.swing.JButton jBtnNum6;
    private javax.swing.JButton jBtnNum7;
    private javax.swing.JButton jBtnNum8;
    private javax.swing.JButton jBtnNum9;
    private javax.swing.JButton jBtnPosNeg;
    private javax.swing.JButton jBtnSubtraktion;
    private javax.swing.JButton jBtnSvar;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}